### ISSUE TITLE
Propose using Terraform and Qovery to deploy Strapi on AWS

### ISSUE THREAD

**Issue by evoxmusic** [61FINTECH/deploy-strapi-on-aws#4]
Hi, I am not sure this guide is still up to date. I would like to propose redirecting people to [this example](https://github.com/Qovery/terraform-examples/tree/main/examples/deploy-strapi-with-postgresql-on-aws) to deploy their Strapi instance on AWS via Terraform and Qovery. WDYT?

**Comment by kenberkeley** [comment]
Look forward to your PR

**Comment by evoxmusic** [comment]
Hi @kenberkeley , thanks for replying so fast :) 

Do you prefer a PR where I redirect people to the example > https://github.com/Qovery/terraform-examples/tree/main/examples/deploy-strapi-with-postgresql-on-aws

Or do you prefer to include the content of the example in this current repo? 

Let me know what fits best you.

**Comment by kenberkeley** [comment]
Oh sorry I suddenly realise I do not have the admin access to this repo...

@xinbaDev Please archive this repo 😂

**Comment by xinbaDev** [comment]
Hi @evoxmusic, feel free to submit a PR and I will help merge it. If not, I will just archive this repo as @kenberkeley suggested.

**Comment by evoxmusic** [comment]
Hi @xinbaDev - I do the PR today.

**Comment by xinbaDev** [comment]
done
